"""
Tests for the Math ↔ Music Transformer module.
"""
import pytest
import sys
import os

# Add src to path
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', 'src'))

from math_music_transformer import (
    MathMusicTransformer, TransformerResult, TransformationStep,
    Direction, get_transformer
)


class TestCoreIsomorphisms:
    """Test the 10 core isomorphisms from the library."""

    def test_cyclic_group_circle_of_fifths(self):
        t = MathMusicTransformer()
        result = t.transform(
            origin_concept="Cyclic group Z_12",
            origin_domain="Mathematics",
            destination_domain="Music",
            structural_property="cyclic group generated by coprime element",
        )
        assert result.direction == "math→music"
        assert "cyclic" in result.isomorphisms[0].lower()
        assert result.total_confidence >= 0.3
        assert result.total_confidence <= 0.99
        assert len(result.steps) == 6
        assert result.steps[0].stage == "PARSE"
        assert result.steps[-1].stage == "VERIFY"

    def test_fourier_overtone_series(self):
        t = MathMusicTransformer()
        result = t.transform(
            origin_concept="Fourier transform",
            origin_domain="Mathematics",
            destination_domain="Music",
            structural_property="decomposition into harmonic components",
        )
        assert "fourier" in result.isomorphisms[0].lower()
        assert "overtone" in result.destination_concept.lower() or "harmonic" in result.destination_concept.lower()

    def test_recursive_function_canon(self):
        t = MathMusicTransformer()
        result = t.transform(
            origin_concept="Recursive function",
            origin_domain="Mathematics",
            destination_domain="Music",
            structural_property="self-referential iteration with base case",
        )
        assert "recursive" in result.isomorphisms[0].lower() or "canon" in result.isomorphisms[0].lower()

    def test_mobius_endless_canon(self):
        t = MathMusicTransformer()
        result = t.transform(
            origin_concept="Möbius strip",
            origin_domain="Mathematics",
            destination_domain="Music",
            structural_property="non-orientable surface with twist",
        )
        assert "mobius" in result.isomorphisms[0].lower() or "mobi" in result.isomorphisms[0].lower()

    def test_symmetry_motivic_inversion(self):
        t = MathMusicTransformer()
        result = t.transform(
            origin_concept="Dihedral group D_4",
            origin_domain="Mathematics",
            destination_domain="Music",
            structural_property="symmetries under reflection and rotation",
        )
        assert "symmetry" in result.isomorphisms[0].lower()

    def test_eigenvalue_resonant_frequency(self):
        t = MathMusicTransformer()
        result = t.transform(
            origin_concept="Eigenvalue",
            origin_domain="Mathematics",
            destination_domain="Music",
            structural_property="invariant under linear operator",
        )
        assert "eigen" in result.isomorphisms[0].lower()

    def test_fibonacci_phasing(self):
        t = MathMusicTransformer()
        result = t.transform(
            origin_concept="Fibonacci sequence",
            origin_domain="Mathematics",
            destination_domain="Music",
            structural_property="recursive growth approaching golden ratio",
        )
        assert "fibonacci" in result.isomorphisms[0].lower() or "golden" in result.isomorphisms[0].lower()

    def test_graph_voice_leading(self):
        t = MathMusicTransformer()
        result = t.transform(
            origin_concept="Complete graph K_n",
            origin_domain="Mathematics",
            destination_domain="Music",
            structural_property="minimal distance between connected nodes",
        )
        assert "graph" in result.isomorphisms[0].lower()

    def test_category_composition(self):
        t = MathMusicTransformer()
        result = t.transform(
            origin_concept="Category theory functor",
            origin_domain="Mathematics",
            destination_domain="Music",
            structural_property="structure-preserving map between categories",
        )
        assert "category" in result.isomorphisms[0].lower()

    def test_topology_tonal_hierarchy(self):
        t = MathMusicTransformer()
        result = t.transform(
            origin_concept="Topological space",
            origin_domain="Mathematics",
            destination_domain="Music",
            structural_property="neighborhood structure encoding proximity",
        )
        assert "topolog" in result.isomorphisms[0].lower()


class TestBidirectionalTransformations:
    """Test music→math direction."""

    def test_music_to_math_fugue(self):
        t = MathMusicTransformer()
        result = t.transform(
            origin_concept="Fugue subject",
            origin_domain="Music",
            destination_domain="Mathematics",
            structural_property="recursive self-referential melodic statement",
        )
        assert result.direction == "music→math"
        assert len(result.steps) == 6
        assert result.total_confidence >= 0.3

    def test_music_to_math_overtone(self):
        t = MathMusicTransformer()
        result = t.transform(
            origin_concept="Overtone series",
            origin_domain="Music",
            destination_domain="Mathematics",
            structural_property="harmonic frequencies as integer multiples",
        )
        assert result.direction == "music→math"
        assert "fourier" in result.isomorphisms[0].lower() or "eigen" in result.isomorphisms[0].lower()

    def test_round_trip_fidelity(self):
        """math→music→language→math round-trip should preserve concept identity."""
        t = MathMusicTransformer()
        result1 = t.transform(
            origin_concept="Cyclic group Z_12",
            origin_domain="Mathematics",
            destination_domain="Music",
            structural_property="cyclic group generated by coprime element",
        )
        # The destination concept should contain musical terminology
        assert any(word in result1.destination_concept.lower() for word in
                    ["fifth", "circle", "tonic", "scale", "harmonic", "interval", "octave"])


class TestTokenLogging:
    """Test token visualization support."""

    def test_tokens_are_logged(self):
        t = MathMusicTransformer()
        test_tokens = ["[PARSE]", "decompose", "group", "[TAG]", "label", "cyclic"]
        result = t.transform(
            origin_concept="Group",
            origin_domain="Mathematics",
            destination_domain="Music",
            structural_property="closure under binary operation",
            tokens=test_tokens,
        )
        assert len(result.tokens_seen) > 0
        assert "PARSE" in str(result.tokens_seen)

    def test_tokens_per_step(self):
        t = MathMusicTransformer()
        test_tokens = ["t1", "t2", "t3", "t4", "t5", "t6", "t7", "t8", "t9", "t10", "t11", "t12", "t13", "t14", "t15", "t16", "t17", "t18"]
        result = t.transform(
            origin_concept="Eigenvalue",
            origin_domain="Mathematics",
            destination_domain="Music",
            structural_property="invariant under operator",
            tokens=test_tokens,
        )
        assert "PARSE" in result.tokens_per_step
        assert "VERIFY" in result.tokens_per_step


class TestConfidenceBounds:
    """Test confidence stays within bounds."""

    def test_confidence_never_below_floor(self):
        t = MathMusicTransformer()
        result = t.transform(
            origin_concept="Something obscure and unrelated",
            origin_domain="Mathematics",
            destination_domain="Music",
            structural_property="vagueness",
        )
        assert result.total_confidence >= 0.3
        assert result.total_confidence <= 0.99

    def test_confidence_high_for_known_isomorphisms(self):
        t = MathMusicTransformer()
        result = t.transform(
            origin_concept="Fourier transform",
            origin_domain="Mathematics",
            destination_domain="Music",
            structural_property="decomposition into harmonic components",
        )
        assert result.total_confidence >= 0.85


class TestBatchTransform:
    """Test batch processing."""

    def test_batch_transform(self):
        t = MathMusicTransformer()
        moves = [
            {"from_concept": "Group", "from_domain": "Mathematics", "to_domain": "Music", "structural_property": "closure"},
            {"from_concept": "Fugue", "from_domain": "Music", "to_domain": "Mathematics", "structural_property": "recursion"},
        ]
        results = t.batch_transform(moves)
        assert len(results) == 2
        assert results[0].direction == "math→music"
        assert results[1].direction == "music→math"


class TestIsomorphismCatalog:
    """Test catalog browsing."""

    def test_catalog_has_all_isomorphisms(self):
        t = MathMusicTransformer()
        catalog = t.get_isomorphism_catalog()
        assert len(catalog) == 10
        assert "cyclic_group__circle_of_fifths" in catalog
        assert "fourier_transform__overtone_series" in catalog


class TestLanguageThread:
    """Test human language as connecting thread."""

    def test_each_step_has_language_thread(self):
        t = MathMusicTransformer()
        result = t.transform(
            origin_concept="Group",
            origin_domain="Mathematics",
            destination_domain="Music",
            structural_property="closure",
        )
        for step in result.steps:
            assert step.language_thread
            assert len(step.language_thread) > 10

    def test_resonance_sentence_generated(self):
        t = MathMusicTransformer()
        result = t.transform(
            origin_concept="Eigenvalue",
            origin_domain="Mathematics",
            destination_domain="Music",
            structural_property="invariant spectrum",
        )
        assert result.resonance_sentence
        assert len(result.resonance_sentence) > 20


class TestSingleton:
    """Test transformer singleton."""

    def test_singleton_returns_same_instance(self):
        t1 = get_transformer()
        t2 = get_transformer()
        assert t1 is t2


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
