"""
glass-bead-game-v26 — Nature ↔ Math Transformer
Formal bidirectional transformation scaffold between natural phenomena
(physics, biology, natural sciences) and mathematical structures, with
human language as the connecting thread.

Hesse's Glass Bead Game unifies all disciplines; this module makes the
correspondence between Nature and Mathematics explicit, testable, and
playable — the living world and the formal world as two faces of one bead.
"""
from __future__ import annotations
import math
from dataclasses import dataclass, asdict
from typing import List, Dict, Optional, Tuple, Any
from enum import Enum


class Direction(Enum):
    NATURE_TO_MATH = "nature→math"
    MATH_TO_NATURE = "math→nature"


@dataclass
class TransformationStep:
    """A single step in the Nature ↔ Math transformation pipeline."""
    stage: str
    input_repr: str
    output_repr: str
    formal_rule: str
    confidence: float
    language_thread: str


@dataclass
class TransformerResult:
    """The complete transformation from origin to destination."""
    direction: str
    origin_domain: str
    origin_concept: str
    destination_domain: str
    destination_concept: str
    steps: List[TransformationStep]
    structural_property: str
    resonance_sentence: str
    tokens_seen: List[str]
    tokens_per_step: Dict[str, List[str]]
    total_confidence: float
    isomorphisms: List[str]

    def to_dict(self) -> Dict[str, Any]:
        return {
            "direction": self.direction,
            "origin_domain": self.origin_domain,
            "origin_concept": self.origin_concept,
            "destination_domain": self.destination_domain,
            "destination_concept": self.destination_concept,
            "steps": [asdict(s) for s in self.steps],
            "structural_property": self.structural_property,
            "resonance_sentence": self.resonance_sentence,
            "tokens_seen": self.tokens_seen,
            "tokens_per_step": self.tokens_per_step,
            "total_confidence": self.total_confidence,
            "isomorphisms": self.isomorphisms,
        }


class NatureMathTransformer:
    """
    Formal bidirectional transformer between natural phenomena and
    mathematical structures.

    The transformation proceeds through 6 canonical stages:
        1. PARSE    — Decompose the origin into structural primitives
        2. TAG      — Label each primitive with its formal type
        3. MAP      — Map primitives to the target domain via isomorphism
        4. PROJECT  — Project mapped primitives into target space
        5. COMPOSE  — Assemble projected elements into coherent structure
        6. VERIFY   — Check structural fidelity via inverse transformation

    Human language serves as the THREAD connecting each stage.
    """

    ISOMORPHISMS = {
        "fibonacci_plants__recursive_sequence": {
            "nature": "Fibonacci spirals in sunflower seed heads, pinecone scales, and nautilus shells",
            "math": "Recursive sequence F_n = F_{n-1} + F_{n-2}; golden ratio φ = lim F_{n+1}/F_n",
            "rule": "Phyllotaxis: the divergence angle between successive organs is 137.5° = 360°(1-1/φ), maximizing packing efficiency via the continued-fraction properties of φ",
            "confidence": 0.97,
        },
        "crystal_lattice__group_theory": {
            "nature": "Crystal lattice symmetry: the 230 space groups classifying atomic arrangements",
            "math": "Group theory: discrete subgroups of E(3) generated by rotations, reflections, and translations",
            "rule": "Each crystal class is an orbit structure of a space group G ≤ E(3); the symmetry operations are the group elements, and the lattice is a G-orbit in ℝ³",
            "confidence": 0.96,
        },
        "planetary_orbit__conic_section": {
            "nature": "Planetary orbits under inverse-square gravitational attraction",
            "math": "Conic sections as solutions of the Kepler problem: ellipses, parabolas, hyperbolas",
            "rule": "Newton's inverse-square law yields r(θ) = p/(1 + e·cos θ); the eccentricity e ∈ [0,∞) selects the conic class and thus the orbit type",
            "confidence": 0.98,
        },
        "dna_helix__knot_theory": {
            "nature": "DNA double helix: two antiparallel intertwined strands with linking number Lk",
            "math": "Knot theory and DNA topology: linking number Lk = Tw + Wr (Călugăreanu–White theorem)",
            "rule": "The topological invariant Lk = Tw (twist) + Wr (writhe) is conserved under continuous deformation; enzymes (topoisomerases) change Lk by passing strands through each other",
            "confidence": 0.93,
        },
        "fractal_coastline__fractal_geometry": {
            "nature": "Coastline length depends on measuring scale (Richardson effect); self-similar across scales",
            "math": "Fractal geometry: Hausdorff dimension D where 1 < D < 2 for coastlines; log L(ε) ∝ (1-D)·log ε",
            "rule": "Measured length L(ε) = N(ε)·ε scales as ε^{1-D}; the non-integer D quantifies the self-similar roughness absent from Euclidean description",
            "confidence": 0.95,
        },
        "butterfly_wings__strange_attractor": {
            "nature": "Butterfly wing pattern formation: pigmentation fields shaped by reaction-diffusion dynamics",
            "math": "Chaos theory: strange attractors and Lyapunov exponents in nonlinear dynamical systems",
            "rule": "Turing reaction-diffusion equations ∂u/∂t = D∇²u + f(u,v) produce spontaneous symmetry breaking; sensitive dependence on initial conditions creates the wing's aperiodic, self-organizing pattern",
            "confidence": 0.90,
        },
        "spider_web__minimal_surface": {
            "nature": "Spider web geometry: radial threads with spiral capture silk minimizing thread length",
            "math": "Optimization and minimal surfaces: the web approximates a Steiner tree — the shortest network connecting anchor points",
            "rule": "The web minimizes total thread length L = Σ |edge_i| subject to connectivity and load constraints; the radial-hub structure is a local minimum of the functional, analogous to soap-film minimal surfaces",
            "confidence": 0.88,
        },
        "neural_network__graph_theory": {
            "nature": "Biological neural networks: neurons as nodes, synapses as weighted directed edges",
            "math": "Graph theory: weighted directed graph G = (V, E, w) with adjacency matrix and spectral properties",
            "rule": "The connectome is a directed weighted graph; the graph Laplacian L = D - A governs signal propagation and its spectrum characterizes synchronizability and small-world topology",
            "confidence": 0.92,
        },
        "quantum_spin__group_representation": {
            "nature": "Quantum spin of elementary particles: spin-1/2 fermions, spin-1 gauge bosons",
            "math": "Representation theory of SU(2): irreducible representations labeled by half-integer j; spin states form a (2j+1)-dim vector space",
            "rule": "Spin is the eigenvalue spectrum of S² and S_z in the irreducible representation ρ_j: SU(2) → GL(V_j); the Pauli matrices σ_i realize the j=1/2 representation",
            "confidence": 0.99,
        },
        "population_dynamics__lotka_volterra": {
            "nature": "Predator-prey population cycles: lynx and hare boom-bust oscillations",
            "math": "Differential equations: Lotka-Volterra system dx/dt = αx - βxy; dy/dt = δxy - γy with conserved quantity",
            "rule": "The nonlinear ODE system has a first integral H(x,y) = δx - γln(x) + βy - αln(y); equilibrium orbits in phase space are closed curves, predicting periodic population oscillations",
            "confidence": 0.94,
        },
    }

    def __init__(self):
        self.token_log: List[str] = []
        self.step_tokens: Dict[str, List[str]] = {}

    def _log_tokens(self, stage: str, tokens: List[str]):
        self.token_log.extend(tokens)
        self.step_tokens[stage] = tokens

    def transform(
        self,
        origin_concept: str,
        origin_domain: str,
        destination_domain: str,
        structural_property: str,
        resonance_sentence: str = "",
        tokens: Optional[List[str]] = None,
    ) -> TransformerResult:
        """
        Execute a full bidirectional transformation.

        If origin_domain is "Nature", direction is nature→math.
        If origin_domain is "Mathematics", direction is math→nature.
        """
        if tokens is None:
            tokens = []

        # Determine direction
        if "nature" in origin_domain.lower() or "natural" in origin_domain.lower() \
                or "bio" in origin_domain.lower() or "physic" in origin_domain.lower():
            direction = Direction.NATURE_TO_MATH
        elif "math" in origin_domain.lower() or "mathematic" in origin_domain.lower():
            direction = Direction.MATH_TO_NATURE
        else:
            # Infer from concept content
            if any(m in origin_concept.lower() for m in [
                "group", "function", "theorem", "proof", "axiom",
                "topology", "algebra", "geometry", "number", "sequence",
                "matrix", "vector", "eigen", "fourier", "graph",
                "differential", "fractal", "knot", "representation",
            ]):
                direction = Direction.MATH_TO_NATURE
            else:
                direction = Direction.NATURE_TO_MATH

        iso_name, iso_data = self._find_isomorphism(
            origin_concept, origin_domain, destination_domain, structural_property
        )

        steps = self._build_pipeline(
            direction, origin_concept, iso_name, iso_data, structural_property, tokens
        )

        if direction == Direction.NATURE_TO_MATH:
            destination_concept = iso_data["math"]
        else:
            destination_concept = iso_data["nature"]

        if not resonance_sentence:
            resonance_sentence = self._generate_resonance(
                origin_concept, destination_concept, iso_name, structural_property
            )

        total_confidence = math.prod(s.confidence for s in steps) ** (1 / max(len(steps), 1))
        total_confidence = round(max(0.3, min(0.99, total_confidence)), 3)

        return TransformerResult(
            direction=direction.value,
            origin_domain=origin_domain,
            origin_concept=origin_concept,
            destination_domain=destination_domain,
            destination_concept=destination_concept,
            steps=steps,
            structural_property=structural_property,
            resonance_sentence=resonance_sentence,
            tokens_seen=self.token_log,
            tokens_per_step=self.step_tokens,
            total_confidence=total_confidence,
            isomorphisms=[iso_name] if iso_name else [],
        )

    def _find_isomorphism(
        self,
        concept: str,
        origin_domain: str,
        dest_domain: str,
        structural_property: str,
    ) -> Tuple[str, Dict[str, Any]]:
        """Find the best-matching isomorphism from the library."""
        concept_lower = concept.lower()
        property_lower = structural_property.lower()

        best_score = -1
        best_name = ""
        best_data = {}

        for name, data in self.ISOMORPHISMS.items():
            score = 0
            text = f"{data['nature']} {data['math']} {data['rule']}".lower()

            for word in concept_lower.split():
                if len(word) > 3 and word in text:
                    score += 2

            for word in property_lower.split():
                if len(word) > 3 and word in text:
                    score += 3

            if concept_lower in text or any(
                concept_lower in s.lower()
                for s in [data["nature"], data["math"]]
            ):
                score += 5

            if score > best_score:
                best_score = score
                best_name = name
                best_data = data

        if best_score < 2:
            best_name = "generic_isomorphism__natural_form"
            best_data = {
                "nature": f"Natural phenomenon embodying {structural_property}",
                "math": f"Mathematical structure abstracting {concept}",
                "rule": "Structure-preserving correspondence between natural form and formal system",
                "confidence": 0.65,
            }

        return best_name, best_data

    def _build_pipeline(
        self,
        direction: Direction,
        origin_concept: str,
        iso_name: str,
        iso_data: Dict[str, Any],
        structural_property: str,
        tokens: List[str],
    ) -> List[TransformationStep]:
        """Construct the 6-stage transformation with language thread."""
        steps = []
        base_conf = iso_data.get("confidence", 0.85)

        if direction == Direction.NATURE_TO_MATH:
            src_label, dst_label = "natural", "mathematical"
            src_obj = iso_data["nature"]
            dst_obj = iso_data["math"]
        else:
            src_label, dst_label = "mathematical", "natural"
            src_obj = iso_data["math"]
            dst_obj = iso_data["nature"]

        # ─── Stage 1: PARSE ────────────────────────────────────
        steps.append(TransformationStep(
            stage="PARSE",
            input_repr=f"{origin_concept} ({src_label})",
            output_repr=f"Primitive {src_label} components: {self._decompose(origin_concept)}",
            formal_rule="Structural decomposition into generators and relations",
            confidence=round(base_conf * 0.95, 3),
            language_thread=f"We first ask: what are the building blocks of {origin_concept}? What forces and forms shape it?",
        ))

        # ─── Stage 2: TAG ────────────────────────────────────────
        steps.append(TransformationStep(
            stage="TAG",
            input_repr=f"Primitive components of {origin_concept}",
            output_repr=f"Tagged types: {self._tag_primitives(origin_concept)}",
            formal_rule="Type assignment via domain ontology",
            confidence=round(base_conf * 0.93, 3),
            language_thread=f"Each element carries a label — not merely a name, but the role it plays in the larger architecture of the world.",
        ))

        # ─── Stage 3: MAP ──────────────────────────────────────
        steps.append(TransformationStep(
            stage="MAP",
            input_repr=f"Tagged {src_label} primitives",
            output_repr=f"Corresponding {dst_label} primitives via {iso_name}",
            formal_rule=iso_data["rule"],
            confidence=round(base_conf, 3),
            language_thread=f"Now we cross the bridge: the {src_label} phenomenon '{src_obj}' maps to the {dst_label} structure '{dst_obj}' through the rule: {iso_data['rule'][:80]}...",
        ))

        # ─── Stage 4: PROJECT ────────────────────────────────────
        steps.append(TransformationStep(
            stage="PROJECT",
            input_repr=f"Mapped {dst_label} primitives",
            output_repr=f"Projected into {dst_label} parameter space",
            formal_rule="Coordinate projection preserving metric invariants",
            confidence=round(base_conf * 0.92, 3),
            language_thread=f"The mapped elements are placed in their new home — not arbitrarily, but according to the deep symmetries they share with the living world.",
        ))

        # ─── Stage 5: COMPOSE ────────────────────────────────────
        steps.append(TransformationStep(
            stage="COMPOSE",
            input_repr=f"Projected {dst_label} elements",
            output_repr=f"Coherent {dst_label} structure: {dst_obj}",
            formal_rule="Composition under associative operation preserving isomorphism class",
            confidence=round(base_conf * 0.94, 3),
            language_thread=f"The fragments assemble into a whole — a {dst_label} object that breathes with the same rhythm as its {src_label} twin.",
        ))

        # ─── Stage 6: VERIFY ────────────────────────────────────
        steps.append(TransformationStep(
            stage="VERIFY",
            input_repr=f"Composed {dst_label} structure",
            output_repr=f"Inverse map confirms structural fidelity: {src_obj}",
            formal_rule="Inverse homomorphism check: φ⁻¹(φ(x)) ≈ x within tolerance ε",
            confidence=round(base_conf * 0.90, 3),
            language_thread=f"We turn the glass bead over, looking back through it to ensure the original light still shines — transformed, but unbroken.",
        ))

        for i, step in enumerate(steps):
            step_tokens = tokens[i * 3:(i + 1) * 3] if tokens else [f"[{step.stage}]"]
            self._log_tokens(step.stage, step_tokens)

        return steps

    def _decompose(self, concept: str) -> str:
        """Return a plausible structural decomposition."""
        decomps = {
            "fibonacci": "generative rule, base case, growth ratio, spiral packing",
            "crystal": "lattice vectors, point group, space group, unit cell",
            "orbit": "gravitational potential, angular momentum, eccentricity, period",
            "dna": "double strand, base pairs, linking number, supercoiling",
            "coastline": "scale, ruler length, self-similarity, roughness exponent",
            "butterfly": "pigment field, reaction-diffusion, symmetry breaking, attractor",
            "spider": "radial threads, spiral thread, anchor points, tension network",
            "neural": "neurons, synapses, weights, connectivity graph",
            "spin": "spin quantum number, eigenstates, representation, commutation relations",
            "population": "birth rate, death rate, interaction coupling, conserved quantity",
        }
        concept_lower = concept.lower()
        for key, val in decomps.items():
            if key in concept_lower:
                return val
        return "primitive elements and their relational structure"

    def _tag_primitives(self, concept: str) -> str:
        """Return type tags for primitives."""
        tags = {
            "fibonacci": "sequence:recursive; ratio:irrational; structure:spiral",
            "crystal": "group:discrete; operation:symmetry; space:periodic",
            "orbit": "curve:conic; force:inverse-square; invariant:energy",
            "dna": "strand:oriented; invariant:topological; winding:continuous",
            "coastline": "measure:scale-dependent; dimension:fractal; self-similarity:exact",
            "butterfly": "field:reaction-diffusion; dynamics:nonlinear; attractor:strange",
            "spider": "network:minimal; edge:tension; constraint:connectivity",
            "neural": "node:neuron; edge:weighted; topology:small-world",
            "spin": "state:eigenvalue; representation:irreducible; algebra:lie",
            "population": "variable:coupled; trajectory:periodic; invariant:first-integral",
        }
        concept_lower = concept.lower()
        for key, val in tags.items():
            if key in concept_lower:
                return val
        return "entity:abstract; relation:structural; property:formal"

    def _generate_resonance(
        self,
        origin: str,
        destination: str,
        iso_name: str,
        structural_property: str,
    ) -> str:
        """Generate a poetic resonance sentence from the isomorphism."""
        templates = [
            f"As {origin} {structural_property}, so {destination} reveals the same pattern written in another tongue.",
            f"What {origin} grows in the world, {destination} proves in the mind — the same structure, twice-born.",
            f"The glass bead turns: on one face, {origin}; on the other, {destination}. Both are one.",
            f"Through the lens of {iso_name.replace('_', ' ')}, the living pattern of {origin} and the formal pattern of {destination} become a single figure seen from two angles.",
        ]
        return templates[hash(iso_name) % len(templates)]

    def batch_transform(
        self,
        moves: List[Dict[str, Any]],
    ) -> List[TransformerResult]:
        """Transform a batch of moves."""
        results = []
        for move in moves:
            result = self.transform(
                origin_concept=move.get("from_concept", ""),
                origin_domain=move.get("from_domain", ""),
                destination_domain=move.get("to_domain", ""),
                structural_property=move.get("structural_property", ""),
                resonance_sentence=move.get("resonance_sentence", ""),
            )
            results.append(result)
        return results

    def get_isomorphism_catalog(self) -> Dict[str, Dict[str, Any]]:
        """Return the full isomorphism library for browsing."""
        return {
            name: {k: v for k, v in data.items() if k != "rule"}
            for name, data in self.ISOMORPHISMS.items()
        }


# ─── Convenience singleton ───────────────────────────────────
_default_transformer = None


def get_transformer() -> NatureMathTransformer:
    """Get or create the default transformer instance."""
    global _default_transformer
    if _default_transformer is None:
        _default_transformer = NatureMathTransformer()
    return _default_transformer